### ISSUE TITLE
Unfamiliar error - Short-circuited in router

### ISSUE THREAD

**Issue by tsinkala** [mwana/mwana#47]
Got following error during testing:
....
[router](Short-circuited): Out <app: ajax> app

[app/handlers]: Incoming message handled by BlastHandler

[router](Short-circuited): In default phase
[router](Short-circuited): Skipping phase
Traceback (most recent call last):
  File "C:\Python26\lib\logging\handlers.py", line 865, in emit
    smtp = smtplib.SMTP(self.mailhost, port)
  File "C:\Python26\lib\smtplib.py", line 239, in **init**
    (code, msg) = self.connect(host, port)
  File "C:\Python26\lib\smtplib.py", line 295, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "C:\Python26\lib\smtplib.py", line 273, in _get_socket
    return socket.create_connection((port, host), timeout)
  File "C:\Python26\lib\socket.py", line 514, in create_connection
    raise error, msg
error: [Errno 10061] No connection could be made because the target machine actively refused it
[backend/pygsm](read:): An exception occurred
Traceback (most recent call last):
  File "C:\rapidSMS\mwana\mwana\submodules\rapidsms\lib\rapidsms\router.py", line 113, in _start_backend
    started = backend.start()
  File "C:\rapidSMS\mwana\mwana\submodules\rapidsms\lib\rapidsms\backends\gsm.py", line 165, in start
    BackendBase.start(self)
  File "C:\rapidSMS\mwana\mwana\submodules\rapidsms\lib\rapidsms\backends\base.py", line 83, in start
    self.run()
  File "C:\rapidSMS\mwana\mwana\submodules\rapidsms\lib\rapidsms\backends\gsm.py", line 128, in run
    msg = self.modem.next_message()
  File "C:\Python26\lib\site-packages\pygsm\gsmmodem.py", line 567, in next_message
    self._fetch_stored_messages()
  File "C:\Python26\lib\site-packages\pygsm\gsmmodem.py", line 546, in _fetch_stored_messages
    messages = self.smshandler.parse_stored_messages(lines)
  File "C:\Python26\lib\site-packages\pygsm\pdusmshandler.py", line 113, in parse_stored_messages
    raise(errors.GsmReadError())
GsmReadError

**Comment by tobiasmcnulty** [comment]
As long as you only see one or two of these at a time, and the route process recovers by itself after the error occurs (which it should), then this is not a problem.  This is just byproduct of using a hardware modem to send/receive messages.

Please confirm that only one or two of these come through at a time, and close the ticket if so.

**Comment by tobiasmcnulty** [comment]
sounds like this has not shown up again - closing
