### ISSUE TITLE
Repeated modem error

### ISSUE THREAD

**Issue by tsinkala** [mwana/mwana#64]
[2010-09-03 16:58:20,960] [backend/pygsm] [DEBUG]: read: 'OK\r\n'
...skipping...
Traceback (most recent call last):
  File "/home/mwana/production/mwana/submodules/rapidsms/lib/rapidsms/router.py", line 113, in _start_backend
    started = backend.start()
  File "/home/mwana/production/mwana/submodules/rapidsms/lib/rapidsms/backends/gsm.py", line 158, in start
    self.modem = pygsm.GsmModem(logger=self.gsm_log,**self.modem_kwargs)
  File "/usr/local/lib/python2.6/dist-packages/pygsm/gsmmodem.py", line 126, in __init__
    self.boot()
  File "/usr/local/lib/python2.6/dist-packages/pygsm/gsmmodem.py", line 243, in boot
    self.set_modem_config()
  File "/usr/local/lib/python2.6/dist-packages/pygsm/gsmmodem.py", line 220, in set_modem_config
    self.command(self.smshandler.get_mode_cmd()      ) # make sure in PDU mode
  File "/usr/local/lib/python2.6/dist-packages/pygsm/gsmmodem.py", line 375, in command
    raise(err)
GsmReadTimeoutError

**Comment by tsinkala** [comment]
Temporal remedy was to reboot

**Comment by tsinkala** [comment]
I don't know if system was overwhelmed. we had at least 522 messages just today

**Comment by tobiasmcnulty** [comment]
again, I believe this error is normal and just a consequence of using a serial modem.  As long as they don't repeat infinitely, it's okay.

**Comment by tsinkala** [comment]
obsolete
