### ISSUE TITLE
Exception in message log

### ISSUE THREAD

**Issue by tsinkala** [mwana/mwana#95]
This is the second time I am seing this exception from the time we started using new rapid sms:

 [2011-09-30 12:39:15,235] [app/messagelog]: An exception occurred
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/rapidsms/router.py", line 438, in outgoing
    continue_sending = func(msg)
  File "/usr/local/lib/python2.7/dist-packages/rapidsms/contrib/messagelog/app.py", line 32, in outgoing
    msg.logger_msg = self._log("O", self._who(msg), msg.text)
  File "/usr/local/lib/python2.7/dist-packages/rapidsms/contrib/messagelog/app.py", line 24, in _log
    **who)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 138, in create
    return self.get_query_set().create(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 360, in create
    obj.save(force_insert=True, using=self.db)
  File "/usr/local/lib/python2.7/dist-packages/rapidsms/contrib/messagelog/models.py", line 51, in save
    models.Model.save(self, _args, *_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 460, in save
    self.save_base(using=using, force_insert=force_insert, force_update=force_update)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 553, in save_base
    result = manager._insert(values, return_id=update_pk, using=using)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 195, in _insert
    return insert_query(self.model, values, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 1436, in insert_query
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 791, in execute_sql
    cursor = super(SQLInsertCompiler, self).execute_sql(None)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 735, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/postgresql_psycopg2/base.py", line 44, in execute
    return self.cursor.execute(query, args)
DatabaseError: current transaction is aborted, commands ignored until end of transaction block

**Comment by tsinkala** [comment]
I just reproduced the issue on my old installation. still investigating

**Comment by lengani** [comment]
I've been seeing this as well. In our case, it seemed to be triggered when
an app tries to modify the same record from two different requests. Still
investigating though.

Regards,

Lengani

On Fri, Sep 30, 2011 at 12:53 PM, tsinkala
<reply+i-1784795-4e5d027b4838a66a3bc390272ef9ed3bbe9a3f55@rep
ly.github.com>wrote:
